---
# njplotディレクトリが存在するか確認
- name: Ensure file "njplot" exists
  file:
    path: /home/{{ansible_info.name}}/package/njplot
    state: "directory"
    owner: "{{ ansible_info.name }}"
    group: "{{ ansible_info.name }}"
    mode: "755"

#解凍ツールのダウンロード
- name: install tar
  dnf:
    name: tar
    state: present

#njplotのインストール
- name: unzip njplot
  unarchive:
    src: package/njplot-2.4.tar.gz
    dest: /home/{{ansible_info.name}}/package/njplot/

#makeのダウンロード
- name: install make
  dnf:
    name: make
    state: present

# 以下今後編集
# - name: njplot make
#   community.general.make:
#     chdir: /home/{{ansible_info.name}}/package/njplot/njplot-2.4