---
- hosts: create_ansibleuser
  tasks:
    - name: Create user
      user:
        name: "{{ uname }}"
        password: "{{ upass | password_hash('sha512') }}"
        group: wheel
        shell: "/bin/bash"

    - name: Ensure dir ".ssh" exists
      file:
        path: /home/{{ uname }}/.ssh
        state: "directory"
        owner: "{{ uname }}"
        group: "{{ uname }}"
        mode: "755"

    - name: Create ssh key
      openssh_keypair:
        path: /home/{{ uname }}/.ssh/id_rsa
        owner: "{{ uname }}"
        type: rsa
        state: present

    - name: Sent pubkey
      authorized_key:
        user: "{{ uname }}"
        state: present
        key: "{{ lookup('file', '/home/{{ uname }}/.ssh/id_rsa.pub')}}"

    - name: Get ssh pubkey
      fetch:
        src: /home/{{ uname }}/.ssh/id_rsa.pub
        dest: ~/tmp/auth_key/
        flat: yes

- hosts: localhost
  tasks:
    - name: Set pubkey
      lineinfile:
        path: /home/{{ ansible_user }}/.ssh/authorized_keys
        line: "{{ lookup('file', '~/tmp/auth_key/id_rsa.pub') }}"
        state: present