---
# パッケージのインストール
- hosts: all
  become: true
  roles:
    - dnf

- hosts: all
  vars:
    install_pkg: "{{ (common_pkg | default([])) + (group_pkg | default([])) + (role_pkg | default([])) + (host_pkg | default([])) }}"
  become: true
  roles:
    - install_packages

# dnfインストール以外のパッケージインストール
# インストールに必要なepelとpipのインストール
- hosts: www
  become: true
  roles:
    - epel
    - pip3

# dnfではインストールできないパッケージのインストール
- hosts: www
  become: true
  roles:
    - install_other_packages