---
- hosts: install_packages_group
  vars:
    install_packages_name:
      "{{ default_install_packages_name }}"
  roles:
    - install_packages

- hosts: A_group
  vars:
    install_packages_name:
      "{{ A_install_packages_name }}"
  roles:
    - install_packages

- hosts: B_group
  vars:
    install_packages_name:
      "{{ B_install_packages_name }}"
  roles:
    - install_packages