# ---
# - hosts: all
#   vars:
#     ansible_user: root
#   roles:
#     - create_user
#     - create_sshkey
#     - auth_key4target

# # - hosts: localhost
# #   roles:
# #     - auth_key4controller

# # パッケージのインストール
# - hosts: all
#   become: true
#   roles:
#     - dnf

# - hosts: all
#   become: true
#   roles:
#     - install_packages

- hosts: pubweb_server
  become: true
  roles:
    - epel
    - pip3
    - r
    - plink
    - fastlmm
    - blast_plus
    - notung
    - clustalw
    - njplot
    - phyml