---
- hosts: replica_server
  tasks:
    - name: check replication status
      shell: >
        mysql -u root --execute="show replica status\G"
      register: replica_status

    - name: show status
      debug:
        var: replica_status['stdout_lines']