---
# blastpディレクトリが存在するか確認
- name: Ensure file "blastp" exists
  file:
    path: /home/{{ansible_info.name}}/package/blastp
    state: "directory"
    owner: "{{ ansible_info.name }}"
    group: "{{ ansible_info.name }}"
    mode: "755"

# rpmファイルをcontrolからコピー
- name: copy rpm file
  copy:
    src: ./package/ncbi-blast-2.17.0+-2.x86_64.rpm
    dest: /home/{{ansible_info.name}}/package/blastp

#blastpのrpmインストール
- name: install blastp
  dnf:
    name: /home/{{ansible_info.name}}/package/blastp/ncbi-blast-2.17.0+-2.x86_64.rpm
    state: installed
    disable_gpg_check: true