---
# wheelグループ作成
- name: Make wheel group
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: "{{ item.state }}"
  with_items:
    "{{ user_groups }}"
  ignore_errors: yes

# ユーザ作成
- name: create local user
  user:
    name: "{{ item.name }}"
    password: "{{ item.pass | password_hash('sha512') }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    comment: "{{ item.comment }}"
    home: "{{ item.home }}"
    createhome: "{{ item.createhome }}"
    state: "{{ item.state }}"
  with_items:
    "{{ user_info }}"
  ignore_errors: yes